### ISSUE TITLE
Live demo or more screenshots

### ISSUE THREAD

**Issue by estevanmaito** [Fried-Chicken/news-outlet#1]
It would be great to see the theme working live, but if that's not possible, at least more screenshots, for the posts page, for example, would help.

**Comment by SimonMo88** [comment]
Hey @estevanmaito, That's a great idea, I'll sort something out.

**Comment by SimonMo88** [comment]
Hey @estevanmaito,

I've now created a demo site [here](https://fried-chicken.github.io/news-outlet/) so I'm closing this issue.

Thanks for raising

@Fried-Chicken
